spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devsu
    username: Admin
    password: DataB_2022
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
server: 
  compression:
    enabled: true
logging: 
  file:
    path: logs
    name: ${logging.file.path}/log.log
  charset: 
    file: UTF-8
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/log_%d{dd-Mm-yyyy}_%i.log
      max-file-size: 2MB
      max-history: 30